// <auto-generated />
namespace FinaceDavid.Resources.Strings;

public static class AppResources
{
    public static string AppTitle => "FINACE DAVID";
    public static string Login_Welcome => "Bem-vindo ao FINACE DAVID";
}
